name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Optional pip cache doesn’t help inside Docker; use BuildKit cache if needed.
      - name: Build test stage
        run: docker build --target test -t ml-api:test .

      - name: Run tests in container
        run: docker run --rm ml-api:test



